### ISSUE TITLE
[1.16.5]启动时游戏卡死

### ISSUE THREAD

**Issue by djp440** [CFPAOrg/I18nUpdateMod2#53]
在1.16.5启动时发现游戏卡死在加载界面，需要手动关闭才能退出，且仅安装该mod的情况下也会发生卡死，版本信息如下图所示
![图片](https://user-images.githubusercontent.com/56632587/209276031-269d83de-eeed-49a6-9eda-a01c82851afe.png)
![图片](https://user-images.githubusercontent.com/56632587/209276053-040be4f3-f110-4ec5-94ed-801e7bd3f104.png)
![图片](https://user-images.githubusercontent.com/56632587/209275880-96478d90-cdaf-43cd-b4e5-770bf362eee9.png)
日志如下
```
[13:23:05] [main/INFO]: ModLauncher running: args [--username, test, --version, 1.16.5, --gameDir, D:\mc\test\.minecraft, --assetsDir, D:\mc\test\.minecraft\assets, --assetIndex, 1.16, --uuid, 530fa97a357f3c1994d30c5c65c18fe8, --accessToken, �7�6�7�6�7�6�7�6�7�6�7�6�7�6�7�6, --userType, legacy, --versionType, HMCL 3.5.3.228, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[13:23:05] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 17.0.4 by GraalVM Community
[13:23:05] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[13:23:05] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/D:/mc/test/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[13:23:06] [main/INFO]: Launching target 'fmlclient' with arguments [--version, 1.16.5, --gameDir, D:\mc\test\.minecraft, --assetsDir, D:\mc\test\.minecraft\assets, --uuid, 530fa97a357f3c1994d30c5c65c18fe8, --username, test, --assetIndex, 1.16, --accessToken, �7�6�7�6�7�6�7�6�7�6�7�6�7�6�7�6, --userType, legacy, --versionType, HMCL 3.5.3.228, --width, 854, --height, 480]
[13:23:06] [main/WARN]: Error loading class: vazkii/patchouli/client/book/BookContents (java.lang.ClassNotFoundException: null)
[13:23:06] [main/WARN]: @Mixin target vazkii.patchouli.client.book.BookContents was not found i18n.mixin.cfg.json:MixinBookContents
[13:23:08] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:23:09] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.AuthenticationUnavailableException: null
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.checkPrivileges(YggdrasilSocialInteractionsService.java:97) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilSocialInteractionsService.<init>(YggdrasilSocialInteractionsService.java:40) ~[authlib-2.1.28.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createSocialInteractionsService(YggdrasilAuthenticationService.java:152) ~[authlib-2.1.28.jar:?]
	at net.minecraft.client.Minecraft.func_244735_a(Minecraft.java:551) ~[?:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:383) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.5.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[13:23:09] [Render thread/INFO]: Setting user: test
[13:23:09] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[13:23:09] [modloading-worker-0/INFO]: Forge mod loading, version 36.2.39, for MC 1.16.5 with MCP 20210115.111550
[13:23:09] [modloading-worker-0/INFO]: MinecraftForge v36.2.39 Initialized

```

**Comment by Inclzw** [comment]
我也遇到了，排除了一堆mod，最后才发现是这个mod的问题
